import '../styles/common.scss';
import '../styles/main.scss';
import '../styles/about-program.scss';
import '../styles/footer.scss';
import '../styles/header.scss';
import '../styles/programs.scss';
import '../styles/want-to-go.scss';
import '../styles/how-to-go.scss';
import '../styles/life-in-israel.scss';
