name: Test Workflow

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
        working-directory: ./israel
